#!/bin/bash

# Base directory for .bbappend files
BASE_DIR="meta-cariq"

# List of original recipes
RECIPES=(
    "meta-ara/recipes-devtools/rootfs-open/rootfs-open.bb"
    "meta-ara/recipes-devtools/osi/osi_3.4.0.bb"
    "meta-ara/recipes-core/images/core-image-apd-devel-radar.bb"
    "meta-ara/recipes-core/images/core-image-apd-testsuiteecu2.bb"
    "meta-ara/recipes-core/images/core-image-apd-devel-fusion.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimal-shm.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimal-radar-fusion.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimal-fusion.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimal-radar-fusion-dds.bb"
    "meta-ara/recipes-core/images/core-image-apd-devel.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimalmachine.bb"
    "meta-ara/recipes-core/images/core-image-apd-devel-wrsomeip.bb"
    "meta-ara/recipes-core/images/core-image-apd-testsuiteecu1.bb"
    "meta-ara/recipes-core/images/ara-sdk.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimal-radar.bb"
    "meta-ara/recipes-core/images/core-image-apd-testsuiteecu1-wrsomeip.bb"
    "meta-ara/recipes-core/images/core-image-apd-devel-shm.bb"
    "meta-ara/recipes-core/images/core-image-apd-minimal-radar-fusion-wrsomeip.bb"
    "meta-ara/recipes-core/images/core-image-apd-testsuiteecu2-wrsomeip.bb"
    "meta-ara/recipes-core/packagegroups/packagegroup-ara-base.bb"
    "meta-ara/recipes-bsw/vsomeip/vsomeip-cfg-ecu1_1.0.0.bb"
    "meta-ara/recipes-bsw/vsomeip/vsomeip-cfg-ecu2_1.0.0.bb"
    "meta-ara/recipes-kernel/linux/firewall-engine_0.1.bb"
    "meta-ara/recipes-apd/apd-cmake-modules/nativesdk-apd-cmake-modules.bb"
    "meta-ara/recipes-apd/apd-cmake-modules/apd-cmake-modules-native.bb"
    "meta-ara/recipes-apd/apd-platform/lib-apd-platform.bb"
    "meta-ara/recipes-apd/gen/ara-gen.bb"
    "meta-ara/recipes-apd/wrapper/ara-wrapper.bb"
    "meta-ara/recipes-apd/wrapper/ara-ifplugd.bb"
    "meta-ara/recipes-apd/wrapper/load-kernel-modules.bb"
    "meta-ara/recipes-apd/wrapper/ara-itm-smtool.bb"
    "meta-ara/recipes-apd/wrapper/ara-can.bb"
    "meta-ara/recipes-apd/wrapper/ara-dropbear.bb"
    "meta-ara/recipes-apd/wrapper/ara-syslogd.bb"
    "meta-ara/recipes-apd/wrapper/ara-getty.bb"
    "meta-ara/recipes-apd/crc/apd-crc.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-updatable-app-v2.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-swcl-base-v1.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-cluster-classic.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-picar-actor-v1.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-picar-controller-v1.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-updatable-app-v1.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-updatable-app-v3.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-picar-controller-v2.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-picar-linesensor-v1.0.0.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-vehicle-packages.bb"
    "meta-ara/recipes-apd/clusters/apd-radarfusionmachine-cluster-picar-ultrasonicsensor-v1.0.0.bb"
    "meta-ara/recipes-apd/rng/apd-rng.bb"
    "meta-ara/recipes-apd/wrsomeip/apd-wrsomeip.bb"
    "meta-ara/recipes-apd/testutils/apd-testutils.bb"
    "meta-ara/recipes-apd/arxmls/apd-applications-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-minimalmachine-network-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-testsuiteecu2wrsomeipmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-common-machine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-radarfusionmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-dlt-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-minimalmachine-interfaces-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-fusionmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-radarfusionwrsomeipmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-minimalmachine-applications-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-radarmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-radarfusionddsmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-cluster-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-testsuiteecu1machine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-testsuiteecu1wrsomeipmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-testsuiteecu2machine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-interfaces-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-shmmachine-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-network-arxmls.bb"
    "meta-ara/recipes-apd/arxmls/apd-minimalmachine-arxmls.bb"
    "meta-ara/recipes-apd/rest/apd-rest-lib_1.0.0.bb"
    "meta-ara/recipes-apd/manifestreader/apd-manifestreader.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-updateadapter-agl.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-cmapp12.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-picar-actor.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-ucm-transfer-performance-check.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-cmvalidatorsubscriber.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-res-tra.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-timesyncconsumer.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-tlvdemoreceiver.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-updatable-app_1.0.0.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-cmapp10.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-vehicle-state-manager-app.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-ucm-vehicle-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-minimalmachine-ucm-vehicle-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-smartcamerasensor.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-secdemofc.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-ddsapp01.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-persistencyredundancydemo.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-cmapp12.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-updateadapter.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-faultycalibrationapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-cmapp03.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-extendedtutorial.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-shmclient1.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-res-tit2.bb"
    "meta-ara/recipes-apd/machines/apd-minimalmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-ddsapp02.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-persistencydemo.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-diagapp01.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-picar-linesensor.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-st-cmapp02.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-cmapp01.bb"
    "meta-ara/recipes-apd/machines/apd-shmmachine-aratsyncdaemon.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-ucm-pkgmgr-sample.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-picar-ultrasonicsensor.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-transfer-performance-check.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-sensordemoapplication.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-st-cmapp11.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-adiosiadapter.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-extendedtutorial.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-shmmaster.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-flashingadapter.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-timesyncprovider.bb"
    "meta-ara/recipes-apd/machines/apd-minimalmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-tlvdemosender.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-st-cmapp09.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-cmapp03.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-updatable-app_1.0.0.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-persistencyredundancydemo.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-faultyreportingapplication.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-ucm-ota-client.bb"
    "meta-ara/recipes-apd/machines/apd-minimalmachine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-st-ddsapp03.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-phmdemo.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-st-cmapp14.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-emosampleapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-faultyprobingapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-radar.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-ucm-vehicle-state-manager-app.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-fusion.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-seciamtestapp.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-radar.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-tlvdemoreceiver.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-picar-linesensor.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-emointegrationtest.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-persistencydemo.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-minimalmachine-systemshutdown.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-updateadapter-agl.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-st-cmapp09.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-flashingadapter.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-res-tit2.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-ddsapp02.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-cmvalidatorpublisher.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-picar-actor.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-cmapp13.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-st-cmapp14.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-ucm-pkgmgr-sample.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-emosampleapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-res-tra-service.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-res-tit.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-st-cmapp02.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-demonstratortutorial.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-osiadiadapter.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-vehicle-driver-app.bb"
    "meta-ara/recipes-apd/machines/apd-shmmachine-shmclient2.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-sensordemoapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-timesyncprovider.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-smtool.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-persistencydemo.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-updatable-app_1.0.0.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-diagapp01.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-fusion.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-timesyncconsumer.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-updateadapter-agl.bb"
    "meta-ara/recipes-apd/machines/apd-shmmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-persistencydemo.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-st-ddsapp03.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-faultyprobingapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-smtool.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-faultycalibrationapplication.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-emoapps.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-demonstratortutorial.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-phmdemo.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-fusion.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-persistencyredundancydemo.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-flashingadapter.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-emosampleapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-ota-client.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-updateadapter-android.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-ucm-vehicle-driver-app.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-cmapp13.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-persistencydemo.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-seciamtestapp.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-secdemofc.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-aratsyncdaemon.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-picar-controller.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-res-tra-service.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-ucm-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-genericadasapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-pkgmgr-sample.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-picar-ultrasonicsensor.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-emointegrationtest.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-timesyncprovider.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-persistencyredundancydemo.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-ucm-vehicle-package-manager.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-cmapp01.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-ddsapp01.bb"
    "meta-ara/recipes-apd/machines/apd-fusionmachine-updateadapter.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-fusion.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-cmvalidatorsubscriber.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-radar.bb"
    "meta-ara/recipes-apd/machines/oem-app.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2wrsomeipmachine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-radar.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-tlvdemosender.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-emosampleapplication.bb"
    "meta-ara/recipes-apd/machines/apd-shmmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-cmvalidatorpublisher.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-aratsyncdaemon.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1wrsomeipmachine-st-emoapps.bb"
    "meta-ara/recipes-apd/machines/apd-radarmachine-updateadapter-android.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-st-cmapp10.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-statemanager.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-timesyncconsumer.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu2machine-st-cmapp11.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-picar-controller.bb"
    "meta-ara/recipes-apd/machines/apd-testsuiteecu1machine-artifacts.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-updateadapter-android.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-res-tra.bb"
    "meta-ara/recipes-apd/machines/apd-minimalmachine-systemrestart.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionwrsomeipmachine-res-tit.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionddsmachine-emosampleapplication.bb"
    "meta-ara/recipes-apd/machines/apd-radarfusionmachine-persistencyredundancydemo.bb"
    "meta-ara/recipes-connectivity/vsomeip/vsomeip_3.1.37.bb"
    "meta-ara/recipes-extended/unit-tests/ara-unit-test-runner.bb"
    "meta-ara/recipes-extended/mbedtls/mbedtls_2.5.1.bb"
    "meta-ara/recipes-extended/dlt-daemon/dlt-daemon-conf-ecu2.bb"
    "meta-ara/recipes-extended/dlt-daemon/dlt-daemon-conf-ecu1.bb"
    "meta-ara/recipes-extended/dlt-daemon/dlt-daemon.bb"
    "meta-ara/recipes-extended/gsl/cpp-core-gsl.bb"
    "meta-ara/recipes-ara/fw/ara-fc-firewall.bb"
    "meta-ara/recipes-ara/fw/tcpserver.bb"
    "meta-ara/recipes-ara/fw/firewall.bb"
    "meta-ara/recipes-ara/phm/ara-phm.bb"
    "meta-ara/recipes-ara/machine-manifest/machine-manifest.bb"
    "meta-ara/recipes-ara/iam/ara-iam.bb"
    "meta-ara/recipes-ara/diagnostic-manager/diagnostic-manager-testsuite.bb"
    "meta-ara/recipes-ara/diagnostic-manager/diagnostic-manager.bb"
    "meta-ara/recipes-ara/diagnostic-manager/diagnostic-manager-st.bb"
    "meta-ara/recipes-ara/diagnostic-manager/diag-arxmls.bb"
    "meta-ara/recipes-ara/log/ara-log.bb"
    "meta-ara/recipes-ara/com/ara-com-lib_1.0.0.bb"
    "meta-ara/recipes-ara/com/libe2exf.bb"
    "meta-ara/recipes-ara/com/libe2e.bb"
    "meta-ara/recipes-ara/core/ara-core.bb"
    "meta-ara/recipes-ara/core/ara-core-types.bb"
    "meta-ara/recipes-ara/ucm/ucm-dpduapi.bb"
    "meta-ara/recipes-ara/ucm/ucm-libs.bb"
    "meta-ara/recipes-ara/ucm/ucm-certs.bb"
    "meta-ara/recipes-ara/ucm/ara-ucm.bb"
    "meta-ara/recipes-ara/sample-applications/diag-integration-test.bb"
    "meta-ara/recipes-ara/sample-applications/wrsomeip-examples.bb"
    "meta-ara/recipes-ara/sample-applications/diag-calculator-example_1.0.0.bb"
    "meta-ara/recipes-ara/sample-applications/ucm-vehicle-driver-app.bb"
    "meta-ara/recipes-ara/sample-applications/diag-seedkey-example_1.0.0.bb"
    "meta-ara/recipes-ara/arxmls/ara-adi-sensoritf-arxmls.bb"
    "meta-ara/recipes-ara/arxmls/ara-arxmls.bb"
    "meta-ara/recipes-ara/tsync/ara-tsync-daemon.bb"
    "meta-ara/recipes-ara/tsync/ara-tsync.bb"
    "meta-ara/recipes-ara/exec/ara-exec_1.0.0.bb"
    "meta-ara/recipes-ara/per/ara-per.bb"
)

# Generic content for most recipes
CONTENT=$(cat << 'EOF'
EXTERNALSRC := "${THISDIR}/../../../../yocto-shared/ara-api"
FILESEXTRAPATHS:prepend := "${THISDIR}/../../../../yocto-shared/ara-api/:"
EOF
)

# Specific content for tcpserver.bb
CONTENT_TCPSERVER=$(cat << 'EOF'
EXTERNALSRC := "${THISDIR}/../../../../yocto-shared/ara-api/fw/test"
FILESEXTRAPATHS:prepend := "${THISDIR}/../../../../yocto-shared/ara-api/fw/test/:"
EOF
)

# Specific content for firewall-engine_0.1.bb
CONTENT_FIREWALL=$(cat << 'EOF'
EXTERNALSRC := "${THISDIR}/../../../../yocto-shared/ara-api/fw/firewall_engine"
FILESEXTRAPATHS:prepend := "${THISDIR}/../../../../yocto-shared/ara-api/fw/firewall_engine:${THISDIR}/../../../../yocto-shared/ara-api/fw/common/:"
EOF
)

# Overwrite .bbappend files with appropriate content
for recipe in "${RECIPES[@]}"; do
    DIR=$(dirname "$recipe" | sed 's/meta-ara/meta-cariq/')
    RECIPE_NAME=$(basename "$recipe" .bb)
    
    mkdir -p "$DIR"
    BBAPPEND_FILE="$DIR/${RECIPE_NAME}.bbappend"
    echo "Updating $BBAPPEND_FILE"
    
    # Apply specific content for tcpserver and firewall-engine, generic for others
    if [ "$recipe" = "meta-ara/recipes-ara/fw/tcpserver.bb" ]; then
        echo "$CONTENT_TCPSERVER" > "$BBAPPEND_FILE"
    elif [ "$recipe" = "meta-ara/recipes-kernel/linux/firewall-engine_0.1.bb" ]; then
        echo "$CONTENT_FIREWALL" > "$BBAPPEND_FILE"
    else
        echo "$CONTENT" > "$BBAPPEND_FILE"
    fi
done

echo "Updated 282 .bbappend files in $BASE_DIR."
